### ISSUE TITLE
Link to unexisting resource

### ISSUE THREAD

**Issue by achikin** [GoThinkster/swift#6]
The step "Read Exploring and Evaluating Swift Code in a Playground" contains a link to unexistent resource https://developer.apple.com/library/ios/recipes/xcode_help-source_editor/chapters/ExploringandEvaluatingSwiftCodeinaPlayground.html

**Comment by thinkclay** [comment]
Thanks for letting us know! Fixed in the repo so it just needs to be pushed (cc: @EricSimons)
